const OPENROUTER_URL='https://openrouter.ai/api/v1/chat/completions';
const fn=(name,description,properties,required=[])=>({type:'function',function:{name,description,parameters:{type:'object',properties,required}}});
const tools=[
fn('get_weather','Get current and multi-day weather from a Sky Pixel place panel.',{place:{type:'string'},day:{type:'string'}}),
fn('compare_weather','Compare weather for multiple Sky Pixel places.',{places:{type:'array',items:{type:'string'}},day:{type:'string'}},['places']),
fn('get_active_place','Get the currently open map place.',{}),
fn('search_atlas','Search the local Sky Pixel Atlas database. Use for lists, capitals, countries, types, and finding names.',{query:{type:'string'},filters:{type:'object',properties:{type:{type:'string'},country:{type:'string'},capital:{type:'boolean'}}}}),
fn('get_place','Get verified details for one Sky Pixel place or country.',{place:{type:'string'}},['place']),
fn('open_map_place','Open a Sky Pixel place on the map. Use for show, take me to, open, locate, or zoom to requests.',{place:{type:'string'}},['place']),
fn('get_nearby','Find nearest stored places by Minecraft block distance.',{place:{type:'string'},type:{type:'string'},limit:{type:'integer'}}),
fn('plan_teleport','Operate the existing visible Teleport Network planner: open it, fill From and To, click Find Route, display the real overlay, and read its result. Use for every teleport route request.',{from:{type:'string'},to:{type:'string'},directOnly:{type:'boolean'},showDirect:{type:'boolean'},showLayover:{type:'boolean'},showThird:{type:'boolean'},showLabels:{type:'boolean'},showExternalTowers:{type:'boolean'}},['to']),
fn('control_teleport_network','Open and configure the existing Teleport Network UI without removing manual controls. Use for direct/layover/third layers, labels, towers, or focus-city requests.',{showDirect:{type:'boolean'},showLayover:{type:'boolean'},showThird:{type:'boolean'},showLabels:{type:'boolean'},showExternalTowers:{type:'boolean'},focusCity:{type:'string'}}),
fn('control_map_interface','Operate an existing Sky Pixel map control without replacing it. Supports night mode, political map, cloud layer, teleport panel, map brightness, teleport labels, and external towers.',{feature:{type:'string'},enabled:{type:'boolean'},value:{type:'number'}} ,['feature'])
];
function cors(){return {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Max-Age':'86400'}}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8',...cors()}})}
function systemPrompt(context){return `You are Atlas, the embedded AI guide and control layer for the Sky Pixel Minecraft world map. Existing buttons, panels, overlays, and manual tools remain available; Atlas only operates them through tools and never claims they were removed. You have tools for weather, local database search, verified place details, map place opening, nearby places, the REAL existing Teleport Network planner, and selected existing interface controls. There is NO road-route tool and NO internet search tool. Never invent Sky Pixel facts or teleport routes. For teleport routes ALWAYS call plan_teleport so the browser operates the existing planner and returns its actual displayed route. For teleport overlay/filter commands call control_teleport_network. For night mode, political map, clouds, brightness, or opening the teleport panel call control_map_interface. For map location commands call open_map_place. Keep answers direct and explicitly state what Atlas changed on the visible map. Runtime context: ${JSON.stringify(context||{})}`}
function safeMessages(input){return (Array.isArray(input.messages)?input.messages:[]).filter(x=>x&&['user','assistant','tool'].includes(x.role)).slice(-30)}
function parseArgs(v){if(v&&typeof v==='object')return v;try{return JSON.parse(v||'{}')}catch{return {}}}
async function callOR(env,body){if(!env.OPENROUTER_API_KEY)throw new Error('OPENROUTER_API_KEY is not configured.');const r=await fetch(OPENROUTER_URL,{method:'POST',headers:{Authorization:`Bearer ${env.OPENROUTER_API_KEY}`,'Content-Type':'application/json','HTTP-Referer':env.SITE_URL||'https://elijah12-12.github.io/Sky-Pixel-World-Map/','X-Title':'Sky Pixel Atlas'},body:JSON.stringify(body)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={error:{message:text}}}if(!r.ok)throw new Error(data?.error?.message||`OpenRouter API failed (${r.status})`);return data}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors()});if(request.method==='GET')return json({ok:true,service:'Sky Pixel Atlas OpenRouter Worker',version:'2.2.0-control-adapter'});if(request.method!=='POST')return json({error:'Use POST.'},405);try{const input=await request.json();const messages=[{role:'system',content:systemPrompt(input.context)},...safeMessages(input)];if(!messages.some(m=>m.role==='user'))messages.push({role:'user',content:String(input.message||'')});const completion=await callOR(env,{model:env.OPENROUTER_MODEL||'openrouter/free',messages,tools,tool_choice:'auto',temperature:0.12,max_tokens:1200});const message=completion?.choices?.[0]?.message||{};const calls=Array.isArray(message.tool_calls)?message.tool_calls:[];if(calls.length)return json({type:'tool_calls',assistantMessage:{role:'assistant',content:message.content||null,tool_calls:calls},calls:calls.map(c=>({id:c.id,name:c.function?.name,arguments:parseArgs(c.function?.arguments)})),model:completion.model});return json({type:'answer',answer:typeof message.content==='string'&&message.content.trim()?message.content.trim():'I could not produce an answer.',model:completion.model});}catch(e){return json({error:e?.message||String(e)},500)}}};
