(function(global){
'use strict';
const normalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const db=()=>global.SKY_PIXEL_ATLAS_DB||{places:[],countries:[],teleport:{edges:[]}};
function allNames(p){return [p.name,...(p.aliases||[])].filter(Boolean)}
function findPlace(name){const q=normalize(name);if(!q)return null;const ps=db().places||[];return ps.find(p=>allNames(p).some(n=>normalize(n)===q))||ps.find(p=>allNames(p).some(n=>normalize(n).includes(q)||q.includes(normalize(n))))||null}
function findCountry(name){const q=normalize(name);return (db().countries||[]).find(c=>[c.name,c.shortName].some(n=>normalize(n)===q||normalize(n).includes(q)||q.includes(normalize(n))))||null}
function search(query,filters={}){const q=normalize(query);let items=(db().places||[]).map(p=>({...p,kind:'place'})).concat((db().countries||[]).map(c=>({...c,kind:'country',type:'country'})));if(filters.type)items=items.filter(i=>normalize(i.type)===normalize(filters.type));if(filters.country)items=items.filter(i=>normalize(i.country||i.shortName)===normalize(filters.country));if(filters.capital===true)items=items.filter(i=>i.capital===true);if(q)items=items.filter(i=>normalize([i.name,i.shortName,i.type,i.country,i.region,...(i.tags||[])].join(' ')).includes(q)||q.split(' ').every(t=>normalize([i.name,i.shortName,i.type,i.country,i.region,...(i.tags||[])].join(' ')).includes(t)));return items.slice(0,50)}
function distance(a,b){if(!a?.coordinates||!b?.coordinates)return null;const dx=a.coordinates.x-b.coordinates.x,dz=a.coordinates.z-b.coordinates.z;return Math.round(Math.sqrt(dx*dx+dz*dz))}
function nearby(name,opts={}){const center=findPlace(name);if(!center?.coordinates)return {ok:false,error:'That place does not have coordinates in Atlas yet.'};const type=opts.type?normalize(opts.type):'';const limit=Math.max(1,Math.min(20,Number(opts.limit)||8));const results=(db().places||[]).filter(p=>p.id!==center.id&&p.coordinates&&(!type||normalize(p.type)===type)).map(p=>({...p,distanceBlocks:distance(center,p)})).sort((a,b)=>a.distanceBlocks-b.distanceBlocks).slice(0,limit);return {ok:true,center,results}}
function teleportPath(from,to){const a=findPlace(from)?.name||from,b=findPlace(to)?.name||to;const edges=db().teleport?.edges||[];const graph={};for(const [x,y] of edges){(graph[x]??=[]).push(y);(graph[y]??=[]).push(x)}if(a===b)return {ok:true,path:[a],hops:0};const queue=[[a]],seen=new Set([a]);while(queue.length){const path=queue.shift(),last=path[path.length-1];for(const next of graph[last]||[]){if(seen.has(next))continue;const np=[...path,next];if(next===b)return {ok:true,path:np,hops:np.length-1};seen.add(next);queue.push(np)}}return {ok:false,error:`No confirmed teleport path is stored between ${a} and ${b}.`}}
function describePlace(name){const p=findPlace(name);if(!p)return {ok:false,error:`Atlas could not find ${name}.`};const country=p.country?findCountry(p.country):null;return {ok:true,place:p,country}}
function exportRuntimeDatabase(){const runtime=global.SkyPixelAtlasActions?.availablePlaceNames?.()||[];const known=new Set((db().places||[]).map(p=>normalize(p.name)));return {version:db().version,missingRuntimePlaces:runtime.filter(n=>!known.has(normalize(n))),database:db()}}
global.SkyPixelAtlasDB=Object.freeze({get:db,findPlace,findCountry,search,nearby,teleportPath,describePlace,distance,exportRuntimeDatabase});
})(window);